name: Bug report
description: Report a problem
body:
  - type: input
    attributes:
      label: Version
      description: "Run `airtable-mcp --version`"
      placeholder: "0.1.3"
    validations:
      required: true
  - type: textarea
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
    validations:
      required: false
